# Generated by Django 3.2.9 on 2021-11-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=40, null=True, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.CharField(blank=True, max_length=255, null=True)),
                ('is_admin', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_staff', models.BooleanField(null=True)),
                ('is_superuser', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
